version: "3.8"

services:
  web:
    build:
      context: scaffoldy
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
      - 8000
    env_file:
      - ./.env.dev.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev.prod.db
  nginx:
    build: nginx/
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
      - ./nginx:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./.env.dev.prod
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
  letsencrypt:

