FROM python:3.9.1-alpine

#RUN mkdir /code
#RUN mkdir /code/staticfiles
#RUN mkdir /code/media
WORKDIR /code

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev git

RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY ./entrypoint.prod.sh .

COPY . .


ENTRYPOINT ["/code/entrypoint.prod.sh"]